/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Rodrigo
 */
public class Imitador2 extends javax.swing.JFrame {

    /**
     * Creates new form Imitador2
     */
    public Imitador2() {
        initComponents();
        
        bg1.add(this.Original_opc1);
        bg1.add(this.Original_opc2);
        bg1.add(this.Original_opc3);
        
        bg2.add(this.espejo_opc1);
        bg2.add(this.espejo_opc2);
        bg2.add(this.espejo_opc3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        original = new javax.swing.JLabel();
        Original_opc1 = new javax.swing.JRadioButton();
        Original_opc2 = new javax.swing.JRadioButton();
        Original_opc3 = new javax.swing.JRadioButton();
        Original_opc4 = new javax.swing.JCheckBox();
        Original_opc5 = new javax.swing.JCheckBox();
        Original_opc6 = new javax.swing.JCheckBox();
        Original_opc7 = new javax.swing.JTextField();
        Original_opc8 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        espejo_opc1 = new javax.swing.JRadioButton();
        espejo_opc2 = new javax.swing.JRadioButton();
        espejo_opc3 = new javax.swing.JRadioButton();
        espejo_opc4 = new javax.swing.JCheckBox();
        espejo_opc5 = new javax.swing.JCheckBox();
        espejo_opc6 = new javax.swing.JCheckBox();
        espejo_opc7 = new javax.swing.JTextField();
        espejo_opc8 = new javax.swing.JComboBox<>();
        espejo = new javax.swing.JLabel();
        Original_opc9 = new javax.swing.JSpinner();
        espejo_opc9 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        original.setText("Original");

        Original_opc1.setText("Opcion 1");
        Original_opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc1ActionPerformed(evt);
            }
        });

        Original_opc2.setText("Opcion 2");
        Original_opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc2ActionPerformed(evt);
            }
        });

        Original_opc3.setText("Opcion 3");
        Original_opc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc3ActionPerformed(evt);
            }
        });

        Original_opc4.setText("Opcion 4");
        Original_opc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc4ActionPerformed(evt);
            }
        });

        Original_opc5.setText("Opcion 5");
        Original_opc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc5ActionPerformed(evt);
            }
        });

        Original_opc6.setText("Opcion 6");
        Original_opc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc6ActionPerformed(evt);
            }
        });

        Original_opc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Original_opc7ActionPerformed(evt);
            }
        });
        Original_opc7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Original_opc7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Original_opc7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Original_opc7KeyTyped(evt);
            }
        });

        Original_opc8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Original_opc8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Original_opc8ItemStateChanged(evt);
            }
        });

        espejo_opc1.setText("Opcion 1");
        espejo_opc1.setEnabled(false);

        espejo_opc2.setText("Opcion 2");
        espejo_opc2.setEnabled(false);

        espejo_opc3.setText("Opcion 3");
        espejo_opc3.setEnabled(false);

        espejo_opc4.setText("Opcion 4");
        espejo_opc4.setEnabled(false);

        espejo_opc5.setText("Opcion 5");
        espejo_opc5.setEnabled(false);

        espejo_opc6.setText("Opcion 6");
        espejo_opc6.setEnabled(false);

        espejo_opc7.setEnabled(false);

        espejo_opc8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        espejo_opc8.setEnabled(false);

        espejo.setText("Espejo");

        Original_opc9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Original_opc9StateChanged(evt);
            }
        });

        espejo_opc9.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(original)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Original_opc1)
                                    .addComponent(Original_opc2)
                                    .addComponent(Original_opc3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Original_opc4)
                                    .addComponent(Original_opc5)
                                    .addComponent(Original_opc6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Original_opc7)
                                    .addComponent(Original_opc8, 0, 117, Short.MAX_VALUE)
                                    .addComponent(Original_opc9)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espejo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(espejo_opc1)
                                    .addComponent(espejo_opc2)
                                    .addComponent(espejo_opc3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(espejo_opc4)
                                    .addComponent(espejo_opc5)
                                    .addComponent(espejo_opc6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(espejo_opc7)
                                    .addComponent(espejo_opc8, 0, 117, Short.MAX_VALUE)
                                    .addComponent(espejo_opc9))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(original)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Original_opc1)
                    .addComponent(Original_opc4)
                    .addComponent(Original_opc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Original_opc2)
                    .addComponent(Original_opc5)
                    .addComponent(Original_opc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Original_opc3)
                    .addComponent(Original_opc6)
                    .addComponent(Original_opc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(espejo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espejo_opc1)
                    .addComponent(espejo_opc4)
                    .addComponent(espejo_opc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espejo_opc2)
                    .addComponent(espejo_opc5)
                    .addComponent(espejo_opc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espejo_opc3)
                    .addComponent(espejo_opc6)
                    .addComponent(espejo_opc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Original_opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc1ActionPerformed
        // TODO add your handling code here:
        this.espejo_opc1.setSelected(this.Original_opc1.isSelected());
    }//GEN-LAST:event_Original_opc1ActionPerformed

    private void Original_opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc2ActionPerformed
        // TODO add your handling code here:
        this.espejo_opc2.setSelected(true);
    }//GEN-LAST:event_Original_opc2ActionPerformed

    private void Original_opc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc3ActionPerformed
        // TODO add your handling code here:
        this.espejo_opc3.setSelected(true);
    }//GEN-LAST:event_Original_opc3ActionPerformed

    private void Original_opc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc4ActionPerformed
        // TODO add your handling code here:
        this.espejo_opc4.setSelected(this.Original_opc4.isSelected());
    }//GEN-LAST:event_Original_opc4ActionPerformed

    private void Original_opc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc5ActionPerformed
        // TODO add your handling code here:
        this.espejo_opc5.setSelected(this.Original_opc5.isSelected());
    }//GEN-LAST:event_Original_opc5ActionPerformed

    private void Original_opc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc6ActionPerformed
        // TODO add your handling code here:
        this.espejo_opc6.setSelected(this.Original_opc6.isSelected());
    }//GEN-LAST:event_Original_opc6ActionPerformed

    private void Original_opc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Original_opc7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Original_opc7ActionPerformed

    private void Original_opc7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Original_opc7KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Original_opc7KeyTyped

    private void Original_opc8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Original_opc8ItemStateChanged
        // TODO add your handling code here:
        this.espejo_opc8.setSelectedIndex(this.Original_opc8.getSelectedIndex());
    }//GEN-LAST:event_Original_opc8ItemStateChanged

    private void Original_opc9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Original_opc9StateChanged
        // TODO add your handling code here:
        this.espejo_opc9.setValue((Integer)this.Original_opc9.getValue());
    }//GEN-LAST:event_Original_opc9StateChanged

    private void Original_opc7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Original_opc7KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_Original_opc7KeyPressed

    private void Original_opc7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Original_opc7KeyReleased
        // TODO add your handling code here:
        this.espejo_opc7.setText(this.Original_opc7.getText());
    }//GEN-LAST:event_Original_opc7KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imitador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imitador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imitador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imitador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imitador2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Original_opc1;
    private javax.swing.JRadioButton Original_opc2;
    private javax.swing.JRadioButton Original_opc3;
    private javax.swing.JCheckBox Original_opc4;
    private javax.swing.JCheckBox Original_opc5;
    private javax.swing.JCheckBox Original_opc6;
    private javax.swing.JTextField Original_opc7;
    private javax.swing.JComboBox<String> Original_opc8;
    private javax.swing.JSpinner Original_opc9;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JLabel espejo;
    private javax.swing.JRadioButton espejo_opc1;
    private javax.swing.JRadioButton espejo_opc2;
    private javax.swing.JRadioButton espejo_opc3;
    private javax.swing.JCheckBox espejo_opc4;
    private javax.swing.JCheckBox espejo_opc5;
    private javax.swing.JCheckBox espejo_opc6;
    private javax.swing.JTextField espejo_opc7;
    private javax.swing.JComboBox<String> espejo_opc8;
    private javax.swing.JSpinner espejo_opc9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel original;
    // End of variables declaration//GEN-END:variables
}
